install:
  postgresql: true
  vault: true
fullnameOverride: ''
nameOverride: ''
imagePullSecrets: []
customLabels: {}
participant:
  id: BPNL00000003AYRE
iatp:
  id: did:web:ssi-dim-wallet-stub.arena2036-x.de:BPNL00000003AYRE
  trustedIssuers:
  - did:web:ssi-dim-wallet-stub.arena2036-x.de:BPNL00000003CRHK
  sts:
    dim:
      url: https://ssi-dim-wallet-stub.arena2036-x.de/api/sts
    oauth:
      token_url: https://ssi-dim-wallet-stub.arena2036-x.de/oauth/token
      client:
        id: BPNL00000003AYRE
        secret_alias: edc-wallet-secret
customCaCerts: {}
controlplane:
  image:
    repository: tractusx/edc-controlplane-postgresql-hashicorp-vault
    pullPolicy: IfNotPresent
    tag: ''
  initContainers: []
  debug:
    enabled: false
    port: 1044
    suspendOnStart: false
  logs:
    level: DEBUG
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  endpoints:
    default:
      port: 8080
      path: /api
    management:
      port: 8081
      path: /management
      authKey: password
      jwksUrl: null
    control:
      port: 8083
      path: /control
    protocol:
      port: 8084
      path: /api/v1/dsp
    metrics:
      port: 9090
      path: /metrics
    catalog:
      port: 8085
      path: /catalog
      authKey: password
  bdrs:
    cache_validity_seconds: 600
    server:
      url: https://ssi-dim-wallet-stub.arena2036-x.de/api/v1/directory
  catalog:
    enabled: false
    crawler:
      num: null
      period: null
      initialDelay: null
      targetsFile: null
  policy:
    validation:
      enabled: true
  service:
    type: ClusterIP
    labels: {}
    annotations: {}
  podLabels: {}
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
  securityContext:
    capabilities:
      drop:
      - ALL
      add: []
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10001
  env: {}
  envValueFrom: {}
  envSecretNames: []
  envConfigMapNames: []
  ingresses:
  - enabled: true
    hostname: a36-edc-controlplane
    annotations: {}
    endpoints:
    - protocol
    - management
    - control
    className: webapprouting.kubernetes.azure.com
    tls:
      enabled: true
      secretName: ''
    certManager:
      issuer: ''
      clusterIssuer: letsencrypt-prod
  - enabled: false
    hostname: edc-control.intranet
    annotations: {}
    endpoints:
    - management
    - control
    className: webapprouting.kubernetes.azure.com
    tls:
      enabled: true
      secretName: ''
    certManager:
      issuer: ''
      clusterIssuer: letsencrypt-prod
  volumeMounts: null
  volumes: null
  resources:
    limits:
      cpu: 1.5
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  opentelemetry: 'otel.javaagent.enabled=false

    otel.javaagent.debug=false'
  nodeSelector: {}
  tolerations: []
  affinity: {}
  url:
    protocol: ''
dataplane:
  image:
    repository: tractusx/edc-dataplane-hashicorp-vault
    pullPolicy: IfNotPresent
    tag: ''
  initContainers: []
  debug:
    enabled: false
    port: 1044
    suspendOnStart: false
  logs:
    level: DEBUG
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  service:
    type: ClusterIP
    labels: {}
    annotations: {}
  endpoints:
    default:
      port: 8080
      path: /api
    public:
      port: 8081
      path: /api/public
    control:
      port: 8084
      path: /api/control
    proxy:
      port: 8186
      path: /proxy
      authKey: password
    metrics:
      port: 9090
      path: /metrics
  token:
    refresh:
      expiry_seconds: 300
      expiry_tolerance_seconds: 10
      refresh_endpoint: null
    signer:
      privatekey_alias: tokenSignerPrivateKey
    verifier:
      publickey_alias: tokenSignerPublicKey
  aws:
    endpointOverride: ''
    accessKeyId: ''
    secretAccessKey: ''
  podLabels: {}
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
  securityContext:
    capabilities:
      drop:
      - ALL
      add: []
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10001
  env: {}
  envValueFrom: {}
  envSecretNames: []
  envConfigMapNames: []
  ingresses:
  - enabled: true
    hostname: a36-edc-dataplane
    annotations: {}
    endpoints:
    - public
    className: webapprouting.kubernetes.azure.com
    tls:
      enabled: true
      secretName: ''
    certManager:
      issuer: ''
      clusterIssuer: letsencrypt-prod
  volumeMounts: null
  volumes: null
  resources:
    limits:
      cpu: 1.5
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  opentelemetry: 'otel.javaagent.enabled=false

    otel.javaagent.debug=false'
  nodeSelector: {}
  tolerations: []
  affinity: {}
  url:
    public: ''
postgresql:
  image:
    repository: bitnamilegacy/postgresql
    tag: 16.2.0-debian-12-r10
  jdbcUrl: jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/edc
  primary:
    persistence:
      enabled: true
  readReplicas:
    persistence:
      enabled: false
  auth:
    database: edc
    username: user
    password: password
vault:
  injector:
    enabled: false
  server:
    dev:
      enabled: true
      devRootToken: root
    postStart: null
  hashicorp:
    url: http://{{ .Release.Name }}-vault:8200
    token: root
    timeout: 30
    healthCheck:
      enabled: true
      standbyOk: true
    paths:
      secret: /v1/secret
      health: /v1/sys/health
      folder: ''
networkPolicy:
  enabled: false
  controlplane:
    from:
    - namespaceSelector: {}
  dataplane:
    from:
    - namespaceSelector: {}
serviceAccount:
  create: true
  annotations: {}
  name: ''
  imagePullSecrets: []
tests:
  hookDeletePolicy: before-hook-creation,hook-succeeded
